name: torneios_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  hive_ce: ^2.4.4
  hive_ce_flutter: ^2.0.0
  icons_launcher: ^2.1.7
  path_provider: ^2.1.4
  supabase_auth_ui: ^0.5.1
  supabase_flutter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  hive_ce_generator: ^1.4.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
